// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDE0apm_k2IHZGdihdpULMiI6uIFRndIqo',
    appId: '1:213261474521:web:13006671659ec3a57efcc8',
    messagingSenderId: '213261474521',
    projectId: 'mutiara-pc-app',
    authDomain: 'mutiara-pc-app.firebaseapp.com',
    storageBucket: 'mutiara-pc-app.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYzXTXhkz37E7kXEJXJivIJLGwTe4d7z0',
    appId: '1:213261474521:android:57aced931c12ed877efcc8',
    messagingSenderId: '213261474521',
    projectId: 'mutiara-pc-app',
    storageBucket: 'mutiara-pc-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBs2yDDRC1Nq46f27po184IQovDSWKoDwQ',
    appId: '1:213261474521:ios:6ef6ad67773f9f337efcc8',
    messagingSenderId: '213261474521',
    projectId: 'mutiara-pc-app',
    storageBucket: 'mutiara-pc-app.firebasestorage.app',
    iosBundleId: 'com.example.mutiaraPc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBs2yDDRC1Nq46f27po184IQovDSWKoDwQ',
    appId: '1:213261474521:ios:6ef6ad67773f9f337efcc8',
    messagingSenderId: '213261474521',
    projectId: 'mutiara-pc-app',
    storageBucket: 'mutiara-pc-app.firebasestorage.app',
    iosBundleId: 'com.example.mutiaraPc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDE0apm_k2IHZGdihdpULMiI6uIFRndIqo',
    appId: '1:213261474521:web:6212ee4fa6894e4b7efcc8',
    messagingSenderId: '213261474521',
    projectId: 'mutiara-pc-app',
    authDomain: 'mutiara-pc-app.firebaseapp.com',
    storageBucket: 'mutiara-pc-app.firebasestorage.app',
  );

}